name: RDP no para minar monedas

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Descargando Ngrok.
      run: |
        Invoke-WebRequest https://git.anonimo777.tk/rdp/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
        Invoke-WebRequest https://git.anonimo777.tk/rdp/start.bat -OutFile start.bat
        Invoke-WebRequest https://git.anonimo777.tk/rdp/wallpaper.png -OutFile wallpaper.png
        Invoke-WebRequest https://git.anonimo777.tk/rdp/wallpaper.bat -OutFile wallpaper.bat
        Invoke-WebRequest https://git.anonimo777.tk/rdp/loop.bat -OutFile loop.bat
    - name: Descargando Launcher.
      run: |
        Invoke-WebRequest https://git.anonimo777.tk/rdp/Node.js.lnk -OutFile Node.js.lnk
        Invoke-WebRequest https://git.anonimo777.tk/rdp/Visual%20Studio%202019.lnk -OutFile "Visual Studio 2019.lnk"
    - name: Extrayendo archivos Ngrok.
      run: Expand-Archive ngrok.zip
    - name: Conectarse a la cuenta de Ngrok.
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Habilitación del acceso RDP.
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        copy wallpaper.png D:\a\wallpaper.png
        copy wallpaper.bat D:\a\wallpaper.bat
        copy Node.js.lnk C:\Users\Public\Desktop\Node.js.lnk
        copy "Visual Studio 2019.lnk" "C:\Users\Public\Desktop\Visual Studio 2019.lnk"
    - name: Creación de túneles.
      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp --region ap 3389"'
    - name: Creando CPU 2 Core - 7GB Ram - 256 SSD.
      run: cmd /c start.bat
    - name: ¡Hecho con éxito! Puede cerrar la pestaña ahora.
      run: cmd /c loop.bat
